/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import View.SplashScreen;

public class App {

    public static void main(String[] args) {
        new SplashScreen().setVisible(true);

    }
}
